### ISSUE TITLE
Github pages loses its DNS connection to docs.raytha.com on build

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#108]
For some reason, whenever we push code to `main` and the github action builds the site documentation, https://docs.raytha.com 404s and I have to go into the settings and re-save the custom domain setting to fix it.

**Comment by divyeshio** [comment]
- Make sure you have selected **None** as source branch
![image](https://user-images.githubusercontent.com/79130336/233770883-40ef5a38-2126-4558-aad8-f542f5694ca6.png)

- Try adding .nojekyll file manually as stated [here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#:~:text=Most%20external%20CI%20workflows%20%22deploy%22%20to%20GitHub%20Pages%20by%20committing%20the%20build%20output%20to%20the%20gh%2Dpages%20branch%20of%20the%20repository%2C%20and%20typically%20include%20a%20.nojekyll%20file.)

- In your dns provider settings make sure, CNAME record for docs.raytha.com is pointing to raytha.github.io , see reference [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#:~:text=If%20you%20want%20to%20use%20the%20subdomain%20another.example.com%20for%20your%20organization%20site%2C%20create%20a%20CNAME%20record%20that%20points%20another.example.com%20to%20%3Corganization%3E.github.io.%20The%20CNAME%20record%20should%20always%20point%20to%20%3Cuser%3E.github.io%20or%20%3Corganization%3E.github.io)

**Comment by apexdodge** [comment]
@divyeshio thanks I will look into it

**Comment by apexdodge** [comment]
@divyeshio was correct. we needed to set the setting to publish from gh actions instead of branch.
