### ISSUE TITLE
Create account crash on empty password

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#153]
In the Create Account screen, if the user enters a password that is at least 1 character, but less than the min password length, they are presented with an error. This behavior is correct.

However, if the user creates an account with a totally empty password field, then it crashes. We should be presented with the same error as the above.

[Login.Commands.CreateUser ](https://github.com/RaythaHQ/raytha/blob/87eedd10d63db398f4817c705dd07f5bb83cd43f/src/Raytha.Application/Login/Commands/CreateUser.cs#L39) 

This if-statement should check for null || < than pw length.

**Comment by takuabonn** [comment]
hi @apexdodge 

I want to work in this issue. will u assign it to me?
