### ISSUE TITLE
TinyMCE throwing errors

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#184]
We have reports that TinyMCE is throwing an error on toLowerCase().

![image](https://github.com/RaythaHQ/raytha/assets/777005/661b6acc-18ec-4257-99eb-a251c55f7a7b)

Further investigation required.

**Comment by fillegar** [comment]
To reproduce, when attempting to Format text from paragraph to H2,  Click Format button on TinyMCE toolbar, Menubar item Format freezes, exception error in browser console at screen shot indicates

**Comment by apexdodge** [comment]
Resolved in `dev` and will be released in v1.2.0. Was a hard issue to debug.

- Upgrading to tinymce 7.0 did not resolve it.
- Upgrading Turbo to 8.0.4 did resolve it.

Theory is the framework was conflicting with tinymce for some reason and turbo made improvements with 8.0
