### ISSUE TITLE
warnings in build vulnerabilities and out of date nuget

### ISSUE THREAD

**Issue by fasteddys** [RaythaHQ/raytha#186]
Helllo, just an FYI, running the ef migrate and build commands

```
The Entity Framework tools version '6.0.1' is older than that of the runtime '8.0.0'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
Done.
```

Also mediator extensions complains its deprecated
![image](https://github.com/RaythaHQ/raytha/assets/96149622/f4b08449-8d85-4ae3-8a76-5ea906c90aac)
_________

So when I tried to update to latest..

![image](https://github.com/RaythaHQ/raytha/assets/96149622/f60fe839-84f8-4f98-9fe5-317d00ec2b04)

**Comment by apexdodge** [comment]
@fasteddys For now you go into Templates > _Layout and edit the template, but #182 for menu management is next up on the roadmap now that #177 is ready.

**Comment by apexdodge** [comment]
Bunch of nuget package clean up and upgraded all packages for v1.2.0.
