### ISSUE TITLE
route template with a "/" in it breaks page css

### ISSUE THREAD

**Issue by vtan31** [RaythaHQ/raytha#195]
I just started getting into it, but I'm a fan of the raytha cms platform.

Seems like any content type that has the route template set with a forward slash "/" in it will break the css styling.  For now, i'm just making sure my routes do not have a forward slash in them,

EX:
https://mccandless-swim.club/Mission-Mahi-5/7-430pm
![image](https://github.com/RaythaHQ/raytha/assets/8713032/a7078d52-95ce-45a6-a713-cade48b29308)

my assets are uploaded to wwwroot folder and pointed to something similar like /quadra/assets/css/theme.css 
my guess is that the forward slash is throwing off the relative location of where the assets are.

if i update it and replace the the "/" to an underscore "_", it works.  
https://mccandless-swim.club/Mission-Mahi-5_7-430pm
![image](https://github.com/RaythaHQ/raytha/assets/8713032/863e0b34-526a-4119-8e2c-d5432bacf63d)

**Comment by apexdodge** [comment]
@vtan31 

Nice website. I'm able to have / in my route template for content types on sites I've built without css issue. I'm curious how you are including the css files to your template. Can you share some code please?

Thanks

**Comment by vtan31** [comment]
i guess the image background for the header could be used as an example.

i modified the original layout template to include a template from themeforest.

![image](https://github.com/RaythaHQ/raytha/assets/8713032/d416e0e2-61a6-48a3-ac79-7f6990f5919e)


	<!-- CSS Files -->
    <link rel="stylesheet" href="quadra/assets/css/plugins.css?v=3.0"/>
    <!-- Main Styles -->
    <link rel="stylesheet" href="quadra/assets/css/theme.css?v=3"/>
        <!-- Blog Styles -->
    <link rel="stylesheet" href="quadra/assets/css/components/quadra/blog.css?v=1.0"/>
    <!-- Color Skins -->
    <link id="changeable_color" rel="stylesheet" href="quadra/assets/css/skins/skin-venus.css" />
    <!-- Index Styles -->
    <link rel="stylesheet" href="quadra/assets/content/index/css/index.css?v3.0" />        


Here's the code for the bg image.
![image](https://github.com/RaythaHQ/raytha/assets/8713032/3b875cc2-46de-46f7-b149-bda6e4aef84c)

       <!-- Home section -->
        <section id="home" class="relative white height-40vh height-30vh-sm mnh-450 align-items-center d-flex" data-bg="url({{ PathBase }}/quadra/assets/images/backgrounds/mcs_pool.jpg)">            
            <!-- Container for titles -->
            <div class="container-md">
                <!-- Start titles -->
                <div class="t-center mt-40">
                    <!-- Title -->
                    <h5 class="fs-24 ls-6 bold white uppercase">
                        <span class="title-highlight-dark">
                            <span>
                            {% if Target.PublishedContent.title.Text %} {{ Target.PublishedContent.title.Text }} {% else %} McCandless Swim Club {% endif %}
                            </span>
                        </span>
                    </h5>                    
                </div>
                <!-- End titles -->
            </div>
            <!-- End Container for titles -->
        </section>
        <!-- End #home section -->

            {% renderbody %}

    <section>
        <div class="container t-center">
            <img src="quadra/assets/images/logos/msc_est.jpg" />
        </div>
    </section>

The home page is just a blog that is using posts...  i duplicated the Content item list view template and created a new template.

![image](https://github.com/RaythaHQ/raytha/assets/8713032/4210fb16-31bf-4fca-bac2-6b20ef403d68)

`    <!-- BLOG -->
    <section id="blog" class="articles-section blog classic blog-list post-shadow lh-lg py-50">
        <!-- <section id="blog" class="articles-section py-50" style="border-bottom:none !important;"> -->
            <!-- Container for blog -->
            <div class="container">
    
                <!-- Row -->
                <div class="row">
    
                    <!-- Col for blog posts -->
                    <div class="col-lg-8 col-12">
                        <!-- Container for posts -->
                        <div id="blog-posts" class="blog-posts">

                            {% if Target.Items.size == 0 %}
                                <p class="fs-24">There are no results, please <a href="home" class="color-primary" style="text-decoration: underline;">reset</a> to see all results.</p>

                            {% else %}
                            
                                {% for item in Target.Items %}                                                        
                                
                                {% assign thumbnail = "quadra/assets/images/blog/swim.jpg" %}

                                {% if item.PublishedContent.thumbnail_url.HasValue %}                                    
                                    {% assign thumbnail =  item.PublishedContent.thumbnail_url %}
                                {% elsif item.PublishedContent.thumbnail.HasValue %}                                    
                                    {% assign thumbnail =  '_static-files/' | append: item.PublishedContent.thumbnail %}
                                {% endif %}

                                {% assign tagsString = item.PublishedContent.category %}
                                {% assign tagsArray = tagsString | split: "," %}

                                <!-- Post -->
                                <figure id="post_01" class="post has-overlay-hover mb-30">
                                    <figcaption class="px-0">
                                        <div class="row mx-0">
                                            <!-- Overlay buttons on left top -->
                                            <div class="absolute overlay-hover slow col-lg-5 col-xs-12 left-0 top-0 zi-50 white fs-18 pt-15 pb-40 dark-corner-left-top pointer-events-none justify-content-start align-items-start">
                                                <!-- <a href="#" class="px-15 py-15 active-me-with-click colored-active pointer-events-all d-inline-flex bg-soft bg-soft-dark2-hover slow circle o-hidden">
                                                    <i class="fas fa-heart"></i>
                                                </a>
                                                <a href="#" target="_blank" class="px-15 py-15 pointer-events-all d-inline-flex bg-soft bg-soft-dark2-hover slow circle o-hidden">
                                                    <i class="fas fa-share-alt"></i>
                                                </a> -->
                                            </div>
                                            <!-- End Overlay buttons on left top -->
                                            <!-- Caption for images -->
                                            <a href="{{ PathBase }}/{{ item.RoutePath }}" class="col-lg-5 col-xs-12 mnh-350 caption bg-center bg-cover" 
                                            data-bg="url('{{ thumbnail }}')">
                                        </a>
                                                                            

                                            <!-- End Caption for images -->
                                            <!-- Details -->
                                            <div class="col-lg-7 col-xs-12 bg-gray2">
                                                <!-- Post Details -->
                                                <a href="{{ PathBase }}/{{ item.RoutePath }}" class="post-details pt-50">
                                                    <div class="fs-16 post-date colored">
                                                        {{ item.CreationTime | organization_time: "%b %e %Y" }}
                                                    </div>
                                                    <h4 class="post-title">
                                                        {{ item.PrimaryField }}
                                                    </h4>
                                                    <p class="post-message">
                                                        {{ item.PublishedContent.content | strip_html | truncate: 280, "..." }}
                                                    </p>
                                                </a>
                                                <!-- End Item Overlay -->
                                                <!-- Tags cloud -->
                                                <div class="tags-cloud d-flex flex-column pb-0">
                                                    <!-- Tags -->
                                                    <div class="marks">

                                                        {% for tag in tagsArray %}
                                                            {% assign trimmedTag = tag | strip %}
                                                            {% assign tagClass = "" %}
        
                                                            {% if trimmedTag == "events" %}
                                                              {% assign tagClass = "bg-pink" %}
                                                            {% elsif trimmedTag == "food_trucks" %}
                                                              {% assign tagClass = "bg-violet" %}
                                                            {% elsif trimmedTag == "membership" %}
                                                              {% assign tagClass = "bg-purple" %}
                                                            {% elsif trimmedTag == "news" %}
                                                              {% assign tagClass = "bg-green" %}
                                                            {% elsif trimmedTag == "swim_team" %}
                                                              {% assign tagClass = "bg-orange" %} 
                                                            {% elsif trimmedTag == "marlins_schedule" %}
                                                              {% assign tagClass = "bg-gold" %}                                                                                                                                                                                         
                                                            {% else %}
                                                              {% assign tagClass = "bg-primary" %}
                                                            {% endif %}

                                                        <a href="home?filter=contains(category,'{{ trimmedTag }}')" class="post-mark white {{tagClass}}">{{ trimmedTag }}</a>

                                                        {% endfor %}
                                                    </div>
                                                    <div class="width-70 height-1 opacity-2 bg-gray6 mt-25"></div>
                                                </div>
                                                <!-- End Tags cloud -->
        
                                                <!-- Author and counts -->
                                                <div class="metas d-flex justify-content-between align-items-end pt-25 pb-45">                                            
                                                    <!-- Read more button -->
                                                    <a href="{{ PathBase }}/{{ item.RoutePath }}" class="fs-12 black t-right underline-slide underline-hover-slide ls-0 semibold uppercase">Read More</a>
                                                </div>
                                                <!-- End Author and counts -->
                                            </div>
                                            <!-- End Details -->
                                        </div>
                                        <!-- End Row -->
                                    </figcaption>
                                </figure>
                                <!-- End Post -->
        
                                {% endfor %}                        
                            {% endif %}

                        </div>
                        <!-- End Container for posts -->
                    </div>
                    <!-- End Col for blog posts -->
    
                    <!-- Side menu -->
                    <aside id="sidemenu" class="sidemenu col-lg-4 col-12">
    
    
                        <!-- Widget -->
                        <div id="search-for-blog" class="widget mb-30">
                            <!-- Search Form -->
                            <div class="cbp-search d-flex align-items-center position-relative w-100 mb-0">
                                <input id="blog-search" type="text" placeholder="Search..." autocomplete="off" data-search="h4" 
                                    class="form-control bg-gray2 classic_form slow dark b-0 py-20 pl-16 pr-4 mb-0 fs-15" value="{{Target.Search}}">
                                <button id="searchIcon" class="btn btn-link position-absolute" style="right: 10px; cursor: pointer;">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                            <!-- End Search Form -->
                        </div>
                        <!-- End Widget -->

                        <!-- Widget - Latest Articles - You can set all text options of article titles here -->
                        <div id="latest_articles" class="fs-16 gray8 ls-0 lh-lg mb-30 bg-gray2 px-40 px-15-sm py-20 py-20-sm">
    
                            <p style="text-align: center;"><span style="font-weight: bold;">McCandless Swimming Club</span><br><span>8300 Thompson Run Rd</span><br><span>Pittsburgh, PA&nbsp; 15237</span><br><br><span><span style="color: #3598db;"><a style="color: #3598db;" href="tel:412-364-4600">412-364-4600</a></span>&nbsp;(Available in the Summer)</span><br><span>Summer : 12 - 8:30pm Sunday - Saturday</span></p>
                            <p style="text-align: center;">&nbsp;</p>
                            <div class="container py-20">
                            <div class="row justify-content-center">
                            <div class="col-auto"><a class="btn btn-success btn-lg" role="button" href="https://app.mccandless-swim.club/registration" target="_blank" rel="noopener"> Register Now </a></div>
                            </div>
                        </div>
                        </div>
                        <!-- End Widget -->                
                         
                        <!-- Widget - Latest Articles - You can set all text options of article titles here -->
                        <div id="latest_articles" class="fs-16 gray8 ls-0 lh-lg mb-30 bg-gray2 px-40 px-15-sm py-20 py-20-sm">

                            <div class="ml-embedded" data-form="p1OJ3i"></div>
                        
                        </div>
                        <!-- End Widget -->  

                        <!-- Widget - Popular Categories - You can set all text options of category titles here -->
                    <div id="popular_categories" class="fs-15 gray8 ls-0 lh-lg mb-30 bg-gray2 px-40 px-15-sm py-50 py-20-sm">
                        <!-- Title -->
                        <h4 class="fs-17 black">
                            Categories
                        </h4>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'events')" class="mt-35 py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-pink">
                            <span class="fs-inherit color-inherit">Events</span>                            
                        </a>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'food_trucks')" class="py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-violet">
                            <span class="fs-inherit color-inherit">Food Trucks</span>                            
                        </a>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'membership')" class="py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-purple">
                            <span class="fs-inherit color-inherit">Membership</span>                            
                        </a>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'news')" class="py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-green">
                            <span class="fs-inherit color-inherit">News</span>                            
                        </a>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'swim_team')" class="py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-orange">
                            <span class="fs-inherit color-inherit">Swim Team</span>                            
                        </a>
                        <!-- Category -->
                        <a href="home?filter=contains(category,'marlins_schedule')" class="py-15 bb-1 b-gray1 colored-hover d-flex align-items-center justify-content-between color-gold">
                            <span class="fs-inherit color-inherit">Swim Team Schedule</span>                            
                        </a>
                    </div>
                    <!-- End Widget - Popular Categories - You can set all text options of category titles here -->
    
                    </aside>
                    <!-- End Side menu -->
    
                </div>
                <!-- End Row -->
    
                <!-- Custom Pagination for the blog -->
                <div class="custom-pagination mt-60 d-flex justify-content-center">
                    <!-- Nav -->
                    <nav aria-label="Post Pagination" class="fullwidth">
                        <!-- List start -->
                        <ul class="pagination justify-content-between d-flex">
                            <li class="page-item mr-auto {% if Target.PreviousDisabledCss %}disabled{% endif %}">
                                <a class="page-link" href="{{ PathBase }}/{{ Target.RoutePath }}?pageNumber={{ Target.PageNumber | minus: 1 }}" aria-label="Previous">
                                    <i class="ti-arrow-left"></i>
                                </a>
                            </li>
                            
                            {% for i in (Target.FirstVisiblePageNumber..Target.LastVisiblePageNumber) %}
                            <li class="page-item {% if Target.PageNumber == i %}active{% endif %}">
                                <a class="page-link" href="{{ PathBase }}/{{ Target.RoutePath }}?pageNumber={{ i }}">{{ i }}</a>
                            </li>
                            {% endfor %}
    
                            {% if Target.LastVisiblePageNumber < Target.TotalPages %}
                            <!-- Active item - .stay class for stay the page -->
                            <li class="page-item disabled">
                                <a class="page-link stay" href="#">...</a>
                            </li>
                            {% endif %}
    
                            <li class="page-item ml-auto {% if Target.NextDisabledCss %}disabled{% endif %}">
                                <a class="page-link" href="{{ PathBase }}/{{ Target.RoutePath }}?pageNumber={{ Target.PageNumber | plus: 1 }}" aria-label="Next">
                                    <i class="ti-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                        <!-- List End -->
                    </nav>
                    <!-- End Nav -->
                </div>
                <!-- End Custom Pagination for the blog -->
    
            </div>
            <!-- End Container for blog -->
    
            <!-- End Container for articles section  -->
            <!-- Left - animated svg element  -->
            <div class="animated-triangle top-percent-5 visible-lg left-0">
                <svg class="fill-colored" width="61px" height="427px" viewBox="0 0 61 427" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g transform="translate(0.000000, -622.000000)" fill-rule="evenodd" stroke="none" stroke-width="1">
                        <polygon points="0 638 0 976 34 906.438761"></polygon>
                    </g>
                </svg>
            </div>
            <!-- End Left - animated svg element  -->
            <!-- Left - animated svg element  -->
            <div class="animated-triangle top-percent-45 visible-lg left-0">
                <svg class="fill-colored" width="61px" height="427px" viewBox="0 0 61 427" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g transform="translate(0.000000, -622.000000)" fill-rule="evenodd" stroke="none" stroke-width="1">
                        <polygon points="0 638 0 976 34 906.438761"></polygon>
                    </g>
                </svg>
            </div>
            <!-- End Left - animated svg element  -->
            <!-- Right - animated svg element  -->
            <div class="animated-triangle top-percent-25 visible-lg right-0">
                <svg class="fill-colored" width="61px" height="427px" viewBox="0 0 61 427" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g transform="translate(-1859.000000, -7379.000000)" fill-rule="evenodd" stroke="none" stroke-width="1">
                        <g transform="translate(0.000000, 5966.000000)">
                            <polygon points="1920 1553 1920 1851 1886 1753.33573"></polygon>
                        </g>
                    </g>
                </svg>
            </div>
            <!-- End Right - animated svg element  -->
            <!-- Right - animated svg element  -->
            <div class="animated-triangle top-percent-65 visible-lg right-0">
                <svg class="fill-colored" width="61px" height="427px" viewBox="0 0 61 427" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <g transform="translate(-1859.000000, -7379.000000)" fill-rule="evenodd" stroke="none" stroke-width="1">
                        <g transform="translate(0.000000, 5966.000000)">
                            <polygon points="1920 1553 1920 1851 1886 1753.33573"></polygon>
                        </g>
                    </g>
                </svg>
            </div>
            <!-- End Right - animated svg element  -->
            
        </section>
        <!-- END BLOG -->
    
    
        <script>
            document.getElementById('searchIcon').addEventListener('click', function() {
                const searchInput = document.getElementById('blog-search').value;                
                    const currentUrl = window.location.href.split('?')[0]; // Get current URL without query string
                    const newUrl = `${currentUrl}?search=${encodeURIComponent(searchInput)}`;
                    window.location.href = newUrl; // Redirect to the new URL                
            });
    
            document.getElementById('blog-search').addEventListener('keypress', function(event) {
                if (event.key === 'Enter') {
                    event.preventDefault();
                    document.getElementById('searchIcon').click();
                }
            });
        </script>
    
    `

so it's weird that i think maybe i need to make the urls absolute and not relative, but i'm not sure how i would do that.  Is there a variable that would handle domain/localhost to get an absolute url for to replace the css stuff?

Hopefully I was able to provide enough information.

Thanks

**Comment by apexdodge** [comment]
@vtan31 

Put a forward slash at the beginning of your relative URL to the resource like below.

`/quadra/assets/css/plugins.css?v=3.0`

Yours does not have that first forward slash. I was able to replicate it in my own demo system. I actually use {{ PathBase }} too just in case I want to change the path base in the future like so:

`<link rel="shortcut icon" href="{{ PathBase }}/raytha_default_2023/assets/images/favicon.ico" type="image/x-icon" />`

Let me know if that helps resolve your issue.
