### ISSUE TITLE
Add github action to automatically build and run tests

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#76]
Since we have made progress on #10, we should consider adding a Github Action that automatically builds and runs the tests when pushed. Then we can get the little badges that says "Builds successful" or "Tests passed"

I like what strapi does: https://github.com/strapi/strapi

- Do they run on every feature branch or just `main` / `dev` / `release-vX.X.X` ?

`main` = current production
`release-vX.X.X` = next minor release (branch off main for minor fixes and minor features)
`dev` = serves as trunk for major feature branches and PRs. Eventually turns into a `release-v.X.X.X` branch when ready to roll out a major release.

**Comment by smd-11** [comment]
Hi @apexdodge ,

Added a Github Action to build and run tests when pushed.

For now i  have tested with branch i have created.

Check this : https://github.com/smd-11/raytha/actions/workflows/tests.yml and let me know if any improvements needed

**Comment by apexdodge** [comment]
@smd-11 

🎉  Please update the branches in tests.yml to be `main` and `dev` and then go ahead and submit PR.

After that, I'll update the readme myself to insert the badge of the workflow status:

![](https://github.com/smd-11/raytha/actions/workflows/tests.yml/badge.svg?branch=excfix)

**Comment by smd-11** [comment]
Done.
