### ISSUE TITLE
Expand Raytha Functions Triggers to support Web hooks

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#82]
We should be able to define web hooks on ContentItem CRUD actions.

#79 is a pre-req

Have to think this one through though. Could be done as a Behavior in the pipeline.

**Comment by smd-11** [comment]
@apexdodge,i would like to work on this. Can you elaborate more what is it that should be achieved

**Comment by apexdodge** [comment]
Webhooks will be possible as a side effect of the expansion in capability of `Raytha Functions` feature in v1.3.0.

The user will be able to select a trigger type, such as Content Item Created / Updated / Deleted and then use the built-in HttpClient object to send a post request externally

Example:

![image](https://github.com/RaythaHQ/raytha/assets/777005/15a2841c-2a3a-44d5-a9b6-06a0b2b7dae5)
