### ISSUE TITLE
Update webpack to satisfy dependabot alert

### ISSUE THREAD

**Issue by apexdodge** [RaythaHQ/raytha#96]
We have a dependabot advisory: https://github.com/RaythaHQ/raytha/security/dependabot/10

https://github.com/RaythaHQ/raytha/blob/9c3510ef3bdd14a0fce58bfdeb8fe00e5d86704e/src/Raytha.Web/wwwroot/raytha_admin/js/package.json#L21

Just need to upgrade the version and then make sure it still builds.

**Comment by Jimreed91** [comment]
Hi, if its sufficient for webpack to build successfully I should be able to do this one!

**Comment by apexdodge** [comment]
@Jimreed91 Thank you!

Merged into `dev` and will be released w/ `v1.0.4`.
